server:
  port: 9090

spring:
  application:
    name: admin-server

  boot:
    admin:
      ui:
        title: "? Microservices Dashboard"
        brand: "Mi Sistema"

management:
  endpoints:
    web:
      exposure:
        include: "*"