#server:
#  port: 8082
#
#spring:
#  application:
#    name: todo-service
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/tareasmicroservicio1?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    username: root
#    password: 1234
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL8Dialect
#        format_sql: true
#
#  security:
#    user:
#      name: admin
#      password: admin123
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: todo-service  # CAMBIA AQUÍ EL NOMBRE
  config:
    import: "configserver:http://localhost:8888"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

# Puerto local (se sobrescribirá por el del config server)
server:
  port: 8080